
worker_processes 1;

events {
  worker_connections 10000;
}

http {

  # NGINX will handle gzip compression of responses from the app server

  gzip on;
  gzip_proxied any;
  gzip_types text/plain application/json;
  gzip_min_length 1000;


  upstream net_automation {

    server 127.0.0.1:8000;

  }


  server {

    listen 80;
    listen 0.0.0.0:443 ssl;
    server_name  mea.infra.chdn.com;

    ssl_certificate /usr/src/app/certs/__infra_chdn_com_cert.cer;
    ssl_certificate_key /usr/src/app/certs/cdilnat_com.key;
    # Nginx will reject anything not matching our api

    location /static/ {
        alias /usr/src/app/static/;

        }

    location /uploads/ {
        alias /usr/src/app/uploads/;

        }

    location / {

      if ($request_method !~ ^(GET|POST|HEAD|OPTIONS|PUT|DELETE)$) {
        return 405;
      }

      # Only requests matching the whitelist expectations will
      # get sent to the application server

      proxy_pass http://fowsio:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';

      proxy_cache_bypass $http_upgrade;

      access_log /var/log/nginx/mea-access_log;
      error_log /var/log/nginx/mea-error_log;

    }


  }
}