# Generated by Django 5.1.4 on 2025-05-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewall',
            old_name='hostname',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='firewall',
            old_name='description',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='firewall',
            old_name='mgmt_ip',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='hostname',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='description',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='mgmt_ip',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='hostname',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='description',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='mgmt_ip',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='config',
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='router',
            name='config',
        ),
        migrations.RemoveField(
            model_name='router',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='config',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='created_on',
        ),
        migrations.AddField(
            model_name='router',
            name='template',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='template',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
    ]
