# Generated by Django 5.1.4 on 2025-05-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0002_rename_hostname_firewall_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='role',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='router',
            name='role',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='switch',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
