# Generated by Django 5.1.4 on 2025-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0003_alter_firewall_role_alter_router_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='template',
            field=models.FileField(upload_to='uploads/router_templates'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='template',
            field=models.FileField(upload_to='uploads/switch_templates'),
        ),
    ]
