# Generated by Django 5.1.4 on 2026-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_app', '0004_alter_router_template_alter_switch_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='FwUpgradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='not_used')),
            ],
        ),
    ]
